# Generated by Django 5.0.8 on 2024-09-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong_ton_kho', models.PositiveIntegerField(default=0)),
                ('ngay_san_xuat', models.DateField()),
                ('ngay_het_han', models.DateField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('danh_muc', models.ManyToManyField(related_name='san_phams', to='category.category')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_cu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_moi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_thay_doi', models.DateTimeField(auto_now_add=True)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_gia', to='product.product')),
            ],
            options={
                'verbose_name': 'Lịch sử giá',
                'verbose_name_plural': 'Lịch sử giá',
                'ordering': ['-ngay_thay_doi'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ten'], name='ten_san_pham_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ngay_san_xuat'], name='ngay_san_xuat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ngay_het_han'], name='ngay_het_han_idx'),
        ),
    ]
