# Generated by Django 5.0.8 on 2024-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorytransaction_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='loai_giao_dich',
            field=models.CharField(choices=[('nhap', 'Nhập hàng'), ('xuat', 'Xuất hàng'), ('tra', 'Trả hàng')], max_length=4),
        ),
    ]
