# Generated by Django 5.0.8 on 2024-10-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorytransaction_loai_giao_dich'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='on_hold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
